services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\EventSubscriber\CategorySubscriber:

    App\EventSubscriber\ProductSubscriber:

    App\EventSubscriber\RoyalFilterSubscriber:

    App\EventSubscriber\WhirlpoolSubscriber:
