services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Vendure\:
        resource: '../../src/Vendure'
        public: true

    App\Vendure\WebhookClient:
        arguments:
            $vendureHost: '%env(VENDURE_HOST)%'
            $vendureWebhookSecret: '%env(VENDURE_WEBHOOK_SECRET)%'

    App\Controller\Api\:
        resource: '../../src/Controller/Api'
        public: true
        tags: ['controller.service_arguments']