services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Vendure\:
        resource: '../../src/Vendure'
        public: true

    App\Vendure\WebhookClient:
        arguments:
            $vendureHost: '%env(VENDURE_HOST)%'
            $vendureWebhookSecret: '%env(PIMCORE_BRIDGE_WEBHOOK_SECRET)%'

    App\Controller\Api\WebhookController:
        arguments:
            $vendureWebhookSecret: '%env(PIMCORE_BRIDGE_WEBHOOK_SECRET)%'
        public: true
        tags: ['controller.service_arguments']
