pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    category-tile:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 150
                                    height: 150
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: category-tile
                        description: 'Category tile image 240x240 (1:1)'
                        group: category
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1766425369
                        creationDate: 1734883200
                        preserveAnimation: false
