pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    category-preview:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 800
                                    height: 500
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: category-preview
                        description: 'Category preview image 800x500 (16:10)'
                        group: category
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1734883200
                        creationDate: 1734883200
                        preserveAnimation: false