opendxp:
    assets:
        image:
            thumbnails:
                definitions:
                    category-tile:
                        items:
                            -
                                method: frame
                                arguments:
                                    width: 300
                                    height: 300
                                    forceResize: true
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#f5f5f5'
                        medias: {  }
                        name: category-tile
                        description: 'Category tile 300x300 (2x retina, contain with padding)'
                        group: category
                        format: JPEG
                        quality: 90
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1711497600
                        creationDate: 1734883200
                        preserveAnimation: false
