services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\GraphQL\Resolver\:
        resource: '../../../src/GraphQL/Resolver'

    ### Layout
    App\GraphQL\Resolver\Layout\NavigationByIdentifierResolver:
        arguments:
            - '@OpenDxp\Bundle\DataHubBundle\GraphQL\Service'
            - '%navigation_allowed_opendxp_class_names%'
