_opendxp:
    resource: "@OpenDxpCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: attribute

deepl_translate_document:
    methods: [ "POST" ]
    path: /admin/deeplTranslateDocument
    controller: App\Controller\DeeplController::deeplTranslateDocument
