imports:
    - { resource: services/vendure.yaml }
    - { resource: services/eventSubscriber.yaml }
    - { resource: services/pimcore.yaml }

    # GRAPHQL
    - { resource: services/graphql/helper.yaml }
    - { resource: services/graphql/mutation.yaml }
    - { resource: services/graphql/query.yaml }
    - { resource: services/graphql/resolver.yaml }
    - { resource: services/graphql/type_response.yaml }
    - { resource: services/graphql/type_argument.yaml }

parameters:
    secret: XOwtGYfiW8T5d0nlwh8UqQ73yLCCWRMDJMMgvjKY20o=
    navigation_allowed_pimcore_class_names:
        - Collection
        - ContentPage
    data_hub_enabled_client_names:
        - frontend

    # customize the full path to external executables
    # normally they are auto-detected by `which program` or auto-discovered in the configured path in
    # System Settings -> General -> Additional $PATH variable
    # but in general it's a good idea to have your programs in your $PATH environment variable (system wide)

    #pimcore_executable_composer: php /opt/vendor/bin/composer.phar
    #pimcore_executable_html2text: /usr/local/html2text/bin/html2text
    #pimcore_executable_soffice: /opt/libreoffice/bin/soffice
    #pimcore_executable_gs: /opt/ghostscript/bin/gs
    #pimcore_executable_pdftotext: /opt/tools/pdftotext
    #pimcore_executable_xvfb-run: /opt/tools/xvfb-run
    #pimcore_executable_pngcrush: /opt/tools/pngcrush
    #pimcore_executable_zopflipng: /opt/tools/zopflipng
    #pimcore_executable_pngout: /opt/tools/pngout
    #pimcore_executable_advpng: /opt/tools/advpng
    #pimcore_executable_cjpeg: /opt/tools/cjpeg
    #pimcore_executable_jpegoptim: /opt/tools/jpegoptim
    #pimcore_executable_php: /usr/local/custom-php/bin/php
    #pimcore_executable_nice: /opt/tools/nice
    #pimcore_executable_nohup: /opt/tools/nohup
    #pimcore_executable_ffmpeg: /opt/tools/ffmpeg
    #pimcore_executable_exiftool: /opt/tools/exiftool
    #pimcore_executable_wkhtmltoimage: /usr/local/bin/wkhtmltoimage
    #pimcore_executable_timeout: /usr/bin/timeout
    #pimcore_executable_facedetect: /usr/bin/facedetect
    # graphviz
    #pimcore_executable_dot: /usr/bin/dot

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    #
    # CONTROLLERS
    #
    App\Controller\:
        resource: '../src/Controller'
        exclude: '../src/Controller/Api/WebhookController.php'
        public: true
        tags: [ 'controller.service_arguments' ]

    #
    # COMMANDS
    #
    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    #
    # SERVICES
    #
    App\Service\:
        resource: '../src/Service/*'
        public: true

    App\Service\DeeplService:
        arguments:
            - '@pimcore.http_client'
            - '%env(DEEPL_AUTH_KEY)%'
            - '%env(DEEPL_GLOSSARY_KEY)%'
            - '%env(DEEPL_ENDPOINT)%'

    App\Service\DeeplProviderService:
        decorates: 'DivanteTranslationBundle\Provider\DeeplProvider'
        arguments:
            - '%env(DEEPL_AUTH_KEY)%'
            - '%env(DEEPL_GLOSSARY_KEY)%'
            - '%env(DEEPL_ENDPOINT)%'

    App\Service\FilterRegistrationNotificationService:
        arguments:
            $adminEmail: '%env(ADMIN_NOTIFICATION_EMAIL)%'

    App\Command\TranslateClassificationStoreCommand:
        arguments:
            $deeplApiKey: '%env(DEEPL_AUTH_KEY)%'
            $sourceLanguage: 'en'
