pimcore:
    general:
        domain: pimcore.royal-filter.com
        redirect_to_maindomain: false
        valid_languages:
            - en
            - de
            - sk
            - cs
        fallback_languages:
            en: ''
            de: en
            sk: en
            cs: en
        required_languages:
            - en
        default_language: en
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
                de: ''
                sk: ''
                cs: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
